{% set name = "python-docx" %}
{% set version = "1.1.0" %}
{% set hash_val = "5829b722141cf1ab79aedf0c34d9fe9924b29764584c0f2164eb2b02dcdf17c9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel

  run:
    - python
    - lxml >=3.1.0
    - typing-extensions

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest >=2.5
    - pyparsing >=2.0.1
  commands:
    - pip check
    - pytest tests -o python_classes=Describe -o python_functions=it_*
  imports:
    - docx
    - docx.dml
    - docx.enum
    - docx.image
    - docx.opc
    - docx.opc.parts
    - docx.oxml
    - docx.oxml.text
    - docx.parts
    - docx.styles
    - docx.text

about:
  home: https://github.com/python-openxml/python-docx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create and update Microsoft Word .docx files.
  description: |
    python-docx is a Python library for reading, creating, 
    and updating Microsoft Word 2007+ (.docx) files.
  dev_url: https://github.com/python-openxml/python-docx
  doc_url: https://python-docx.readthedocs.io/

extra:
  recipe-maintainers:
    - pmlandwehr
    - nicoddemus
