{% set name = "python-docx" %}
{% set version = "1.1.0" %}
{% set hash_val = "5829b722141cf1ab79aedf0c34d9fe9924b29764584c0f2164eb2b02dcdf17c9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python =2.7|>=3.4

  run:
    - python =2.7|>=3.4
    - lxml >=2.3.2

test:
  imports:
    - docx
    - docx.dml
    - docx.enum
    - docx.image
    - docx.opc
    - docx.opc.parts
    - docx.oxml
    - docx.oxml.text
    - docx.parts
    - docx.styles
    - docx.text

about:
  home: https://github.com/python-openxml/python-docx
  license: MIT
  license_file: LICENSE
  summary: Create and update Microsoft Word .docx files.

extra:
  recipe-maintainers:
    - pmlandwehr
    - nicoddemus
