{% set name = "python-docx" %}
{% set version = "0.8.11" %}
{% set hash_val = "1105d233a0956dd8dd1e710d20b159e2d72ac3c301041b95f4d4ceb3e0ebebc4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python

  run:
    - python
    - lxml >=2.3.2

test:
  imports:
    - docx
    - docx.dml
    - docx.enum
    - docx.image
    - docx.opc
    - docx.opc.parts
    - docx.oxml
    - docx.oxml.text
    - docx.parts
    - docx.styles
    - docx.text

about:
  home: https://github.com/python-openxml/python-docx
  license: MIT
  license_file: LICENSE
  summary: Create and update Microsoft Word .docx files.

extra:
  recipe-maintainers:
    - pmlandwehr
    - nicoddemus
