{% set name = "python-docx" %}
{% set version = "1.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7bc9d7b7d8a69c9c02ca09216118c86552704edc23bac179283f2e38f86220ce

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=61.0.0
    - wheel
  run:
    - python
    - lxml >=3.1.0
    - typing-extensions >=4.9.0

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest >=8.4.0
    - pyparsing >=3.2.3
  commands:
    - pip check
    - pytest tests -o python_classes=Describe -o python_functions=it_*
  imports:
    - docx
    - docx.dml
    - docx.enum
    - docx.image
    - docx.opc
    - docx.opc.parts
    - docx.oxml
    - docx.oxml.text
    - docx.parts
    - docx.styles
    - docx.text

about:
  home: https://github.com/python-openxml/python-docx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create and update Microsoft Word .docx files.
  description: |
    python-docx is a Python library for reading, creating, 
    and updating Microsoft Word 2007+ (.docx) files.
  dev_url: https://github.com/python-openxml/python-docx
  doc_url: https://python-docx.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - nicoddemus
