travis:
  secure:
    BINSTAR_TOKEN: X89LM3fQf1n6MZDFu36x8LseHJr6kttROvc6fp0ZauCHxa5Z1jdCpA0uBI1LEbow85hye0Tol1H7X0FWxPJB4C9hO9T268ZHNjvCInRr5lFOaP24t7o4JkoysJMHRLkaW2gUUPAvkhAxFzjKA4EZ0+mCXHHHuvu4T97I7XH228uic454OUZPlrfnYYiPNuEvuIYKV1ky99kwJFZi7lKxBzNNtN/MxVhr+SuW5VKa4M3BZTz7Iukt+IpFldXlYorNzus+UA+2q+FpmPFab4It82DF9QUHpm7B0HEHxE/01LCfec8z03g2RDm0ibfKuqdFnwoum8Upu8IKB+DNrCNZIm+48EERO9ee7Tvt+2amkDVB6xZvq7hUmQ3xhoP+0i3UgLWm4gdqVAmSB+vqVY0ohYElOnX6sVlPCZ0Fl7Y8smiEjh6Ultx8+KCro5JiWstARfDdXXu3T4yCib6OSSxoovMgHMPSnM/2HaDsGqlG21CKD1UIm7iz19L5BkBSLxbJXjiG5lAQRU5dOpKZb9VjBLBoaH8llpU4HdGx1uhGl4zaULIr0PiCNnaWVlBPe/AjMCHPsi7Q0eDx+MEhdUYjI5QTTBbL4vIej3z/hNXEBSAPn4FU6LGRKqdr6ZVT/w5d/0dgDevFbf6evjFvF8ST8rB4UlUbHWbSZJdB/jUVvQA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
