travis:
  secure:
    BINSTAR_TOKEN: YPk3Hej6wcYTjXdb7VyHEELt4SHR4TY9WcLeK2FNWSmH/zi0bWFiVppug3Bg4E8FbLIyZtC2i9VOWHsqrVndPoEBu+LPDtI4FRwcrJOl3ic7B9vV9nrN0U6TDfv3csmF0jntJwOslgd/olLNJB26+F6cK0ueOXp8JYtzsU1HIVq6qlA3JwdcjqaYm98FQ0gcIQJCrUGLUt87t0eedQ1j4dosZ3mlZ1NtK8jTfgBv8UMADcLWp8Uto8qF9IZrnCWi8oCSXze5xNjwiFHbjGPXj+bwDvx8wq1Cim/GG5P6011aCzHs9Mhfn8XvkbGspCQ/kWQmkyB9uDUmsavqCFWgfs6Ecjik0XGRJ7D+Qp/IDiOSxiUA1460IMAj/ig70geMzzDjfUb24oD8VaIdnkinIu81/TYPE2Mz3nTd2s7EEMXvjdtVmx20vEmt33E2QxKkiDAvxjYZPrByz5ilb+U70QU5Dp/EuCpxeJM6JkofAOu/ldQUoIwNPSYJNEdJLUJv5qksWL0ZhMNcpng1RPgM5ZDr+Jb3Ri12nk17MwuY76z3r5hoJaz08jXBjoOCBdzIi2FA+X9KZlma4HjwrikXCuvImSSA7+/Ef6hdreul+G1KmwdVQLlyjM7oCY+8CFdqUgmNsIgCnQ2E8lhImHjEpnfPw5Okwz3uknFZzzBLphU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
