travis:
  secure:
    BINSTAR_TOKEN: R+H2CWILi8Lan6KP99IM+b95/UmOhBBdQZ6BT6k0/V/tAoRGskIT6FFRtvIJCNuIgsS7kcZcyCOijgUZuzm5n6pArgAhFNBHevNtHf+CBJVB+qKkfPu/MwsMeSSgsJ+uJzitsR+gEJNd8HoOX95SKsQ0oUW9xt8o2GWp5JaaktJs0E9209N3e8C3uQ6kPc5PO83/MilgkwCjx9F10/sgmUfqnejJcEy1KkS1bblGP6/8UAboPsK5tHrq09HvQ0Sk0pZYFM4tz5W3Fmhuv4znijxzVeunmWCkNNg5Cucv41b00/9GZnC1qDSqgOGsqiU47n4+7/gT1Ivp61qrukesif7187F3UKRMvkHZI1uyG1AHSWJ1LYyj6tNwJV2QEyyszQjMLDxgerWxJ6hicpLLvubQHFtDLy9lFNEV69FSwoZLEv9U9mUxiq8eLYTLleJ6HHEsndTHG58SHvadjxwX72xXtX0+vpIbGLx/5Q8W9xRSpW8OpxXHuRA9z1F9EECkLa/oCFObVVBuv5k7IhDruxaPhjZ5NICDfeyIeqUWi7C72+QIuQ8QMz3G2y/ajpzMze9SUrAveAsV7TKmSNT7pTdfl64yk13KMDpftFyj+ImjLi1WfwKdBh7MyEb3mF4lZgmz6lDlqdPsf9YITiolGr2uQvkgudXVcoqXWNCGWFU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
